[package]
name = "tinypixel"
version = "0.1.0"
authors = ["Togglebit <me@togglebit.io>"]
edition = "2018"

[dependencies]
winit = "0.23.0"
wgpu = "0.6.2"
futures = "0.3.7"
bytemuck = "1.4.1"
euclid = "0.22.1"
